package dk.grixie.oauth2.app.model;

public enum MessageType {
    AUTHORIZATION_CODE_GRANT_REQUEST,
    AUTHORIZATION_CODE_GRANT_RESPONSE,
    ACCESS_TOKEN_ACQUIRED,
    ACCESS_TOKEN_NOT_ACQUIRED,
    REFRESH_TOKEN,
    GET_TIME_REQUEST,
    GET_TIME_RESPONSE,
    GET_ATTRIBUTES_REQUEST,
    GET_ATTRIBUTES_RESPONSE,
    GET_MESSAGE_REQUEST,
    GET_MESSAGE_RESPONSE,
    SET_MESSAGE_REQUEST,
    SET_MESSAGE_RESPONSE,
    OPEN_WEB_SOCKET_REQUEST,
    OPEN_WEB_SOCKET_RESPONSE,
    CLOSE_WEB_SOCKET_REQUEST,
    CLOSE_WEB_SOCKET_RESPONSE,
    ECHO_REQUEST,
    ECHO_RESPONSE,

}
